import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { useApi, useData, useRefresh, useIdentity, params, cardUrl, clozeText, type Card, type Collection, type Page } from '../../lib/workspace'
import { Icon, Markdown, PageHeading, QueryState } from '../../components/Common'
import { CardPicker } from '../../components/Selectors'

type Item = Card & { item_id: string; position: number }
export function Cover({ collection }: { collection: Collection }) { return <div className={`cover cover-${collection.cover_color} cover-${collection.cover_style}`}><div className="cover-art"/><span>{collection.title}</span><small>{collection.total_items} 张卡片</small></div> }
function shuffle(ids: string[]) { return [...ids].map(value => ({ value, sort: Math.random() })).sort((a, b) => a.sort - b.sort).map(e => e.value) }
export default function Collections() {
  const { id } = useParams()
  return <CollectionWorkspace key={id || 'all'}/>
}
function CollectionWorkspace() {
  const { id } = useParams(), [search, setSearch] = useSearchParams(), [message, setMessage] = useState(''), [picker, setPicker] = useState(false), [reveal, setReveal] = useState(false)
  const api = useApi(), refresh = useRefresh()
  const { guest, openLogin } = useIdentity()
  const listing = useData<Page<Collection>>(`/collections?${params({ is_favorite: search.get('favorite') === 'true' || undefined, q: search.get('q'), limit: 100 })}`)
  const collection = useData<Collection>(`/collections/${id}`, !!id), directory = useData<{ items: Item[]; revision: number }>(`/collections/${id}/items`, !!id)
  const random = search.get('mode') === 'random', reading = search.get('view') === 'read', requested = search.get('item')
  const [randomOrder, setRandomOrder] = useState<string[]>([])
  const active = useMemo(() => directory.data?.items.filter(c => c.lifecycle === 'active') || [], [directory.data])
  const previous = useRef<{ ids: string[]; item: string | null }>({ ids: [], item: null })
  const [fallback, setFallback] = useState<string | null>(null)
  // Preserve a neighboring position when an externally updated member directory removes the current item.
  // oxlint-disable-next-line react/set-state-in-effect
  useEffect(() => { const old = previous.current; if (requested && !active.some(c => c.item_id === requested)) { const n = Math.max(0, old.ids.indexOf(requested)); setFallback(active[Math.min(n, active.length - 1)]?.item_id || null) } else setFallback(null); previous.current = { ids: active.map(c => c.item_id), item: requested } }, [active, requested])
  // Preserve the reader's random session order across server refreshes, appending only new members.
  // oxlint-disable-next-line react/set-state-in-effect
  useEffect(() => { setRandomOrder(old => { const ids = active.map(c => c.item_id); const kept = old.filter(v => ids.includes(v)); const added = ids.filter(v => !old.includes(v)); if (kept.length === old.length && !added.length) return old; return [...kept, ...shuffle(added)] }) }, [active])
  const sequence = random ? randomOrder.map(v => active.find(c => c.item_id === v)).filter((v): v is Item => !!v) : active
  const index = Math.max(0, sequence.findIndex(c => c.item_id === (fallback || requested))), current = sequence[index]
  function update(values: Record<string, string>) { const next = new URLSearchParams(search); Object.entries(values).forEach(([k, v]) => v ? next.set(k, v) : next.delete(k)); setSearch(next) }
  const navigateItem = useCallback((n: number) => { if (sequence[n]) { const next = new URLSearchParams(search); next.set('item', sequence[n].item_id); next.set('view', 'read'); setSearch(next) } }, [sequence, search, setSearch])
  // An external directory update or URL navigation begins a new card reveal interaction.
  // oxlint-disable-next-line react/set-state-in-effect
  useEffect(() => { setReveal(false) }, [current?.item_id])
  useEffect(() => { function key(e: KeyboardEvent) { if (!reading || ['INPUT', 'TEXTAREA', 'SELECT', 'BUTTON', 'A'].includes((e.target as HTMLElement).tagName) || (e.target as HTMLElement).isContentEditable) return; if (e.key === 'ArrowLeft') navigateItem(index - 1); if (e.key === 'ArrowRight') navigateItem(index + 1); if (e.code === 'Space') { e.preventDefault(); setReveal(v => !v) } } window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [reading, index, navigateItem])
  async function mutate(path: string, method: string, body: object) { try { await api(path, method, { ...body, expected_revision: collection.data!.revision }); setMessage(''); await refresh() } catch (error) { setMessage((error as Error).message) } }
  async function reorder(itemId: string, step: number) { const items = directory.data!.items.map(c => c.item_id), n = items.indexOf(itemId), target = n + step; if (target < 0 || target >= items.length) return; [items[n], items[target]] = [items[target], items[n]]; await mutate(`/collections/${id}/order`, 'PUT', { item_ids: items }) }
  return <><PageHeading title="合集" description="把散落的卡片串起来，在翻阅中遇见新的连接。"><Link className="button primary" to="/collections/new">＋ 新建合集</Link></PageHeading><div className="workspace-layout collection-layout"><aside className="sidebar"><p className="eyebrow">我的合集</p><button className={!search.get('favorite') ? 'active' : ''} onClick={() => update({ favorite: '' })}><Icon name="grid"/>全部合集<span>{listing.data?.total ?? '—'}</span></button><button className={search.get('favorite') ? 'active' : ''} onClick={() => update({ favorite: search.get('favorite') ? '' : 'true' })}><Icon name="bookmark"/>收藏合集</button><div className="sidebar-divider"/><QueryState query={listing}>{listing.data?.items.map(c => <Link className={`collection-nav ${id === c.id ? 'active' : ''}`} key={c.id} to={`/collections/${c.id}?view=read`}><Cover collection={c}/><div><b>{c.title}</b><small>{c.knowledge_count} 知识 · {c.opinion_count} 观点</small></div></Link>)}</QueryState></aside><section className="workspace-main">
    {!id ? <><div className="toolbar"><div className="search-box"><Icon name="search"/><input aria-label="搜索合集" placeholder="搜索合集…" value={search.get('q') || ''} onChange={e => update({ q: e.target.value })}/></div></div><QueryState query={listing} empty={listing.data?.total === 0}><div className="collection-grid">{listing.data?.items.map(c => <Link className="collection-tile" key={c.id} to={`/collections/${c.id}?view=read`}><Cover collection={c}/><h3>{c.title}</h3><p>{c.available_items} 张可翻阅卡片 · {c.knowledge_count} 知识 / {c.opinion_count} 观点</p></Link>)}</div></QueryState></> : <QueryState query={collection}>{collection.data && <><div className="collection-head"><div><h2>{collection.data.title}</h2><Markdown text={collection.data.description_md}/><p>{collection.data.total_items} 张卡片 · {collection.data.knowledge_count} 知识 / {collection.data.opinion_count} 观点</p></div><button aria-label="收藏合集" aria-pressed={collection.data.is_favorite} onClick={() => void mutate(`/collections/${id}`, 'PATCH', { is_favorite: !collection.data!.is_favorite })}><Icon name="bookmark"/></button></div><div className="toolbar"><div className="segmented"><button className={reading ? 'selected' : ''} onClick={() => update({ view: 'read' })}>翻阅卡片</button><button className={!reading ? 'selected' : ''} onClick={() => update({ view: 'directory' })}>卡片目录</button></div><select aria-label="翻阅顺序" value={random ? 'random' : 'ordered'} onChange={e => update({ mode: e.target.value === 'random' ? 'random' : '' })}><option value="ordered">顺序翻阅</option><option value="random">随机翻阅</option></select><button onClick={() => guest ? openLogin() : setPicker(!picker)}>＋ 添加卡片</button></div><p role="status">{message}</p>{picker && <CardPicker excluded={directory.data?.items.map(c => c.id)} onSelect={c => { void mutate(`/collections/${id}/items`, 'POST', { card_ids: [c.id] }); setPicker(false) }}/>}
    <QueryState query={directory}>{reading ? current ? <><div className="reader-progress"><span>{index + 1} / {sequence.length} 张可翻阅卡片</span><span className="muted">← → 切换 · 空格揭示答案</span></div><article className={`reader-card panel ${current.kind === 'opinion' ? 'opinion-reader' : ''}`}><div className="card-meta"><span>{current.kind === 'knowledge' ? '知识卡片' : '观点卡片'}</span><Link to={cardUrl(current)}>打开原卡 ↗</Link></div><h2>{current.title}</h2><div className="reader-content"><Markdown text={current.kind === 'opinion' ? current.body_md : current.form === 'qa' ? current.question_md : clozeText(current.body_md || '', reveal)}/>{current.kind === 'knowledge' && current.form === 'qa' && reveal && <div className="answer"><Markdown text={current.answer_md}/></div>}</div>{current.kind === 'knowledge' && <button className="reveal" onClick={() => setReveal(!reveal)}>{reveal ? '隐藏答案' : '显示答案'}</button>}</article><div className="reader-controls"><button disabled={index === 0} onClick={() => navigateItem(index - 1)}>← 上一张</button><span>{current.kind === 'knowledge' ? '知识' : '观点'} · {index + 1} / {sequence.length}</span><button disabled={index >= sequence.length - 1} onClick={() => navigateItem(index + 1)}>下一张 →</button></div><p className="reader-note">翻阅是一段自由阅读的时间。想巩固记忆，可以前往 <Link to="/knowledge/review">知识复习 ↗</Link></p></> : <div className="state panel"><h3>还没有可翻阅的卡片</h3><p>添加知识或观点卡片，开始这段阅读。</p><button onClick={() => guest ? openLogin() : setPicker(true)}>添加卡片</button></div> : <div className="directory panel">{directory.data?.items.map((c, n) => <div key={c.item_id} className="directory-row"><span>{n + 1}</span><div><b>{c.title}</b><small>{c.kind === 'knowledge' ? '知识' : '观点'}{c.lifecycle !== 'active' && ' · 暂不可用'}</small></div><button aria-label={`上移 ${c.title}`} disabled={!n} onClick={() => void reorder(c.item_id, -1)}>↑</button><button aria-label={`下移 ${c.title}`} disabled={n === directory.data!.items.length - 1} onClick={() => void reorder(c.item_id, 1)}>↓</button><button aria-label={`移除 ${c.title}`} onClick={() => void mutate(`/collections/${id}/items/${c.item_id}`, 'DELETE', {})}>移除</button></div>)}</div>}</QueryState>
    <div className="collection-actions"><Link to={`/collections/${id}/edit`}>编辑合集</Link><button onClick={() => void mutate(`/collections/${id}`, 'PATCH', { is_pinned: !collection.data!.is_pinned })}>{collection.data.is_pinned ? '取消主页置顶' : '置顶到主页'}</button><button onClick={() => void mutate(`/collections/${id}/lifecycle`, 'POST', { action: collection.data!.lifecycle === 'active' ? 'trash' : 'restore' })}>{collection.data.lifecycle === 'active' ? '移入回收站' : '恢复合集'}</button></div></>}</QueryState>}
  </section></div></>
}
