import { useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useApi, useData, useRefresh, params, cardUrl, clozeText, type Card, type Label, type Page, type ReviewSummary } from '../../lib/workspace'
import { Icon, Markdown, PageHeading, Pager, QueryState, Tags } from '../../components/Common'

function Flashcard({ card }: { card: Card }) {
  const [reveal, setReveal] = useState(false), [message, setMessage] = useState('')
  const detail = useData<Card>(`/cards/${card.id}`, reveal)
  const api = useApi(), refresh = useRefresh()
  async function bookmark() { try { await api(`/cards/${card.id}`, 'PATCH', { expected_revision: card.revision, is_bookmarked: !card.is_bookmarked }); await refresh() } catch (e) { setMessage((e as Error).message) } }
  return <article className="flashcard"><div className="card-meta"><span>{card.topics[0]?.name || '未分类'}</span><button aria-label={`${card.is_bookmarked ? '取消收藏' : '收藏'} ${card.title}`} aria-pressed={card.is_bookmarked} onClick={() => void bookmark()}><Icon name="bookmark"/></button></div><Link className="card-title" to={cardUrl(card)}>{card.title}</Link><p className="excerpt">{card.excerpt}</p>{reveal && <div className="flash-answer"><QueryState query={detail}><Markdown text={detail.data?.form === 'qa' ? detail.data.answer_md : clozeText(detail.data?.body_md || '', true)}/></QueryState></div>}<div className="card-bottom"><Tags items={card.tags}/><button className="reveal-link" aria-expanded={reveal} onClick={() => setReveal(!reveal)}>{reveal ? '收起答案' : '查看答案'} <span>↗</span></button></div>{message && <p role="alert">{message}</p>}</article>
}
export default function Knowledge() {
  const [search, setSearch] = useSearchParams(), [view, setView] = useState('grid')
  const q = search.get('q') || '', topic = search.get('topic') || '', offset = Number(search.get('offset') || 0), bookmarked = search.get('bookmarked') === 'true', lifecycle = search.get('lifecycle') || 'active'
  const topics = useData<{ items: Label[] }>('/topics?kind=knowledge'), tags = useData<{ items: Label[] }>('/tags')
  const cards = useData<Page<Card>>(`/cards?${params({ kind: 'knowledge', q, topic_id: topic, tag_id: search.get('tag'), lifecycle, is_bookmarked: bookmarked || undefined, sort: search.get('sort') || 'updated_desc', limit: 12, offset })}`)
  const summary = useData<ReviewSummary>('/reviews/summary'), totals = useData<{ knowledge: number }>('/cards/summary')
  function update(key: string, value: string) { const next = new URLSearchParams(search); if (value) next.set(key, value); else next.delete(key); if (key !== 'offset') next.delete('offset'); setSearch(next) }
  return <><PageHeading title="知识" description="让每一次回忆，都成为更牢固的理解。"><Link className="button primary" to="/knowledge/review">开始复习 <span>→</span></Link></PageHeading><div className="workspace-layout"><aside className="sidebar"><p className="eyebrow">我的知识库</p><button className={!topic && !bookmarked && lifecycle === 'active' ? 'active' : ''} onClick={() => setSearch({})}><Icon name="book"/>全部知识<span>{totals.data?.knowledge ?? '—'}</span></button><button className={bookmarked ? 'active' : ''} onClick={() => update('bookmarked', bookmarked ? '' : 'true')}><Icon name="bookmark"/>我的收藏</button><button onClick={() => update('lifecycle', lifecycle === 'archived' ? '' : 'archived')} className={lifecycle === 'archived' ? 'active' : ''}><Icon name="card"/>已归档</button><div className="sidebar-divider"/><p className="eyebrow">分类</p><QueryState query={topics}>{topics.data?.items.map(t => <button className={topic === t.id ? 'active' : ''} key={t.id} onClick={() => update('topic', t.id)}><span className="category-dot"/>{t.name}<span>{t.card_count}</span></button>)}</QueryState><Link className="sidebar-add" to="/new?kind=knowledge">＋ 新建知识卡片</Link><div className="sidebar-note"><Icon name="book"/><h3>记住，更要理解。</h3><p>先尝试主动回忆，再揭示答案。小步积累，自有回响。</p></div></aside>
    <section className="workspace-main"><div className="review-strip"><div><small>今日目标</small><b>{summary.data?.today_completed ?? '—'} <em>/ {summary.data?.daily_review_goal ?? '—'} 个复习单元</em></b><div className="progress-track"><span style={{ width: `${summary.data ? Math.min(100, summary.data.today_completed / summary.data.daily_review_goal * 100) : 0}%` }}/></div></div><div><small>待复习</small><b>{summary.data?.due_units ?? '—'} <em>个复习单元</em></b></div><div><small>已掌握</small><b>{summary.data?.mastered_cards ?? '—'} <em>张卡片</em></b></div><Icon name="calendar"/></div>{summary.error && <QueryState query={summary}/>}
      <div className="toolbar"><div className="search-box"><Icon name="search"/><input aria-label="搜索知识" placeholder="搜索知识、标签或关键词…" value={q} onChange={e => update('q', e.target.value)}/></div><select aria-label="知识标签" value={search.get('tag') || ''} onChange={e => update('tag', e.target.value)}><option value="">全部标签</option>{tags.data?.items.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select><select aria-label="知识排序" value={search.get('sort') || 'updated_desc'} onChange={e => update('sort', e.target.value)}><option value="updated_desc">最近更新</option><option value="created_desc">最近创建</option><option value="code_asc">编号顺序</option></select><button aria-label="切换卡片布局" onClick={() => setView(view === 'grid' ? 'list' : 'grid')}><Icon name="grid"/></button></div>
      <div className="section-title"><h2>{lifecycle === 'archived' ? '已归档' : topic ? topics.data?.items.find(t => t.id === topic)?.name : bookmarked ? '收藏知识' : '全部知识'} <small>{cards.data?.total ?? 0} 张卡片</small></h2><span className="muted">慢慢学，牢牢记。</span></div><QueryState query={cards} empty={cards.data?.total === 0}><div className={`card-grid ${view === 'list' ? 'list-view' : ''}`}>{cards.data?.items.map(c => <Flashcard key={c.id} card={c}/>)}</div>{cards.data && <Pager {...cards.data} onChange={n => update('offset', String(n))}/>}</QueryState></section></div></>
}
