import { test, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

const shots = '../../docs/design/card-navigation-v1/guest'
test('guest four-page browsing, readonly actions, deep links and mobile touch', async ({ page }) => {
  await mkdir(shots, { recursive: true })
  const requests: string[] = []
  page.on('request', r => { if (new URL(r.url()).pathname.startsWith('/api/')) requests.push(`${r.method()} ${new URL(r.url()).pathname}`) })
  await page.route('**/api/**', async route => {
    const path = new URL(route.request().url()).pathname
    if (path === '/api/auth/me') await route.fulfill({ status: 401, json: { detail: '请先登录' } })
    else if (path === '/api/auth/config') await route.fulfill({ json: { registration_enabled: true } })
    else await route.abort()
  })
  await page.setViewportSize({ width: 1586, height: 992 })
  await page.goto('/knowledge')
  await expect(page.getByText('演示空间 · 只读')).toBeVisible()
  await expect(page.getByRole('link', { name: '主动回忆为什么有效？', exact: true })).toBeVisible()
  await page.screenshot({ path: `${shots}/01-knowledge.png`, fullPage: true })
  await page.getByLabel('搜索知识').fill('主动回忆为什么')
  await expect(page.getByRole('button', { name: /查看答案/ })).toHaveCount(1)
  await page.getByRole('button', { name: /查看答案/ }).click()
  await expect(page.getByText(/主动回忆是先不看材料/)).toBeVisible()
  await page.getByRole('button', { name: '取消收藏 主动回忆为什么有效？' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('tab', { name: '注册' })).toBeVisible()
  await page.getByRole('button', { name: '关闭登录窗口' }).click()
  await page.goto('/opinions?card=de000000-0000-4000-8000-000000000007')
  await expect(page.getByRole('heading', { name: '笔记的价值在于连接', level: 2 })).toBeVisible()
  await page.screenshot({ path: `${shots}/02-opinions.png`, fullPage: true })
  await page.getByRole('link', { name: '主动回忆为什么有效？', exact: true }).first().click()
  await expect(page).toHaveURL(/knowledge\/cards\/de000000/)
  await expect(page.getByText(/主动回忆是先不看材料/)).toHaveCount(0)
  await page.goto('/collections/de000000-0000-4000-8000-000000000301?view=read')
  await expect(page.getByRole('heading', { name: '主动回忆为什么有效？', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '下一张 →' }).click()
  await expect(page.getByRole('heading', { name: '用填空记住学习过程' })).toBeVisible()
  await expect(page.getByText(/主动提取/)).toHaveCount(0)
  await page.getByRole('button', { name: '显示答案' }).click()
  await expect(page.getByText(/主动提取/)).toBeVisible()
  await page.screenshot({ path: `${shots}/03-collections.png`, fullPage: true })
  await page.getByLabel('翻阅顺序').selectOption('random')
  await page.reload()
  await expect(page.getByText('演示空间 · 只读')).toBeVisible()
  await expect(page.getByRole('button', { name: '下一张 →' })).toBeVisible()
  await page.getByRole('button', { name: '＋ 添加卡片' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: '关闭登录窗口' }).click()
  await page.goto('/me')
  await expect(page.getByRole('heading', { name: '演示账号', exact: true })).toBeVisible()
  await expect(page.locator('.heat-cell[title]')).toHaveCount(84)
  await page.screenshot({ path: `${shots}/04-profile.png`, fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: `${shots}/05-profile-mobile.png`, fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('navigation', { name: '移动端导航' }).getByRole('link', { name: '知识' }).tap()
  await expect(page.getByRole('link', { name: '主动回忆为什么有效？', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('link', { name: '开始复习 →' }).tap()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('heading', { name: '在自己的空间继续' })).toBeVisible()
  expect(requests.every(r => r === 'GET /api/auth/me' || r === 'GET /api/auth/config')).toBe(true)
})
