import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useApi, useIdentity, useData, useRefresh, params, type Profile, type Session, type Page, type Label, type Card, type Collection } from '../../lib/workspace'
import { PageHeading, QueryState } from '../../components/Common'
import { usernamePattern } from '../../lib/registration'

export default function Account({ logout }: { logout: () => Promise<void> }) {
  const { session } = useIdentity(), api = useApi(), navigate = useNavigate()
  const [current, setCurrent] = useState(''), [password, setPassword] = useState(''), [message, setMessage] = useState('')
  async function change(e: FormEvent) { e.preventDefault(); try { await api('/auth/change-password', 'POST', { current_password: current, new_password: password }); window.dispatchEvent(new Event('session-expired')); navigate('/knowledge') } catch (error) { setMessage((error as Error).message) } }
  return <><PageHeading title="设置" description={`用户名：${session?.username} · ${session?.role === 'admin' ? '管理员' : '普通用户'}`}/><div className="settings-layout"><ProfileForm/><section className="panel single-form"><h2>账号</h2><div className="account-actions">{session?.role === 'admin' && <button onClick={() => navigate('/admin/users')}>管理用户</button>}<button onClick={() => void logout()}>退出登录</button><Link to="/trash">回收站</Link></div><form onSubmit={e => void change(e)}><h3>修改密码</h3><label>当前密码<input type="password" required value={current} autoComplete="current-password" onChange={e => setCurrent(e.target.value)}/></label><label>新密码（至少 8 个字符）<input type="password" required minLength={8} maxLength={128} value={password} autoComplete="new-password" onChange={e => setPassword(e.target.value)}/></label><button>更新密码</button><p role="status">{message}</p></form></section></div><TaxonomySettings/></>
}
function ProfileForm() {
  const query = useData<Profile>('/me/profile'), api = useApi(), refresh = useRefresh()
  const [draft, setDraft] = useState<Profile | null>(null), [message, setMessage] = useState(''), [interests, setInterests] = useState('')
  // Initialize once from the asynchronous profile; subsequent refreshes retain the draft.
  // oxlint-disable-next-line react/set-state-in-effect
  useEffect(() => { if (query.data && !draft) { setDraft(query.data); setInterests(query.data.interests.join('，')) } }, [query.data, draft])
  async function save(e: FormEvent) { e.preventDefault(); if (!draft) return; try { const result = await api<Profile>('/me/profile', 'PATCH', { expected_revision: draft.revision, display_name: draft.display_name, bio: draft.bio, avatar_color: draft.avatar_color, timezone: draft.timezone, daily_new_limit: draft.daily_new_limit, daily_review_goal: draft.daily_review_goal, interests: interests.split(/[,，]/).map(v => v.trim()).filter(Boolean) }); setDraft(result); setMessage('个人资料已保存。'); await refresh() } catch (error) { setMessage((error as Error).message) } }
  return <section className="panel single-form"><h2>个人资料与学习偏好</h2><QueryState query={query}>{draft && <form onSubmit={e => void save(e)}><label>昵称<input maxLength={80} required value={draft.display_name} onChange={e => setDraft({ ...draft, display_name: e.target.value })}/></label><label>个人简介<textarea rows={3} maxLength={2000} value={draft.bio} onChange={e => setDraft({ ...draft, bio: e.target.value })}/></label><label>兴趣标签（逗号分隔）<input value={interests} onChange={e => setInterests(e.target.value)}/></label><label>头像颜色<select value={draft.avatar_color} onChange={e => setDraft({ ...draft, avatar_color: e.target.value })}><option value="sage">鼠尾草绿</option><option value="clay">陶土</option><option value="ink">墨色</option></select></label><label>时区<input value={draft.timezone} required onChange={e => setDraft({ ...draft, timezone: e.target.value })}/></label><label>每日新单元额度<input type="number" min={0} max={100} value={draft.daily_new_limit} onChange={e => setDraft({ ...draft, daily_new_limit: Number(e.target.value) })}/></label><label>每日复习目标<input type="number" min={1} max={1000} value={draft.daily_review_goal} onChange={e => setDraft({ ...draft, daily_review_goal: Number(e.target.value) })}/></label><p role="status">{message}</p><div className="inline-form"><button className="primary">保存资料</button><button type="button" onClick={() => { void query.refetch().then(({ data }) => { if (data) { setDraft(data); setInterests(data.interests.join('，')); setMessage('已恢复服务器资料。') } }) }}>恢复服务器内容</button></div></form>}</QueryState></section>
}
export function AdminUsers() {
  const api = useApi(), { session, refresh: refreshSession } = useIdentity(), refresh = useRefresh()
  const [offset, setOffset] = useState(0), query = useData<Page<Session>>(`/admin/users?limit=20&offset=${offset}`, session?.role === 'admin')
  const [username, setUsername] = useState(''), [password, setPassword] = useState(''), [message, setMessage] = useState('')
  async function create(e: FormEvent) { e.preventDefault(); try { await api('/admin/users', 'POST', { username, password }); setUsername(''); setPassword(''); setMessage('账号已创建。'); await refresh() } catch (error) { setMessage((error as Error).message) } }
  async function update(user: Session, changes: object) { try { await api(`/admin/users/${user.id}`, 'PATCH', changes); await refresh(); if (user.id === session?.id) await refreshSession() } catch (error) { setMessage((error as Error).message) } }
  if (session?.role !== 'admin') return <p>无管理权限。</p>
  return <><PageHeading title="用户" description="管理账号的角色与可用状态。"><Link to="/settings">返回账号</Link></PageHeading><div className="panel single-form"><form onSubmit={e => void create(e)}><h2>创建普通用户</h2><label>用户名<input required value={username} pattern={usernamePattern} maxLength={32} onChange={e => setUsername(e.target.value)}/></label><label>初始密码（至少 8 个字符）<input required type="password" minLength={8} value={password} onChange={e => setPassword(e.target.value)}/></label><button>创建账号</button></form><p role="status">{message}</p><QueryState query={query}>{query.data?.items.map(u => <div className="user-row" key={u.id}><span><b>{u.username}</b><small>{u.role === 'admin' ? '管理员' : '普通用户'} · {u.is_active ? '可用' : '已停用'}</small></span><button onClick={() => void update(u, { is_active: !u.is_active })}>{u.is_active ? '停用' : '启用'}</button><button onClick={() => void update(u, { role: u.role === 'admin' ? 'member' : 'admin' })}>{u.role === 'admin' ? '降为普通用户' : '设为管理员'}</button></div>)}</QueryState><div className="pager"><button disabled={!offset} onClick={() => setOffset(offset - 20)}>上一页</button><span>{query.data?.total} 位用户</span><button disabled={offset + 20 >= (query.data?.total || 0)} onClick={() => setOffset(offset + 20)}>下一页</button></div></div></>
}
export function Trash() {
  const [type, setType] = useState('cards'), [offset, setOffset] = useState(0), [message, setMessage] = useState('')
  const query = useData<Page<Card | Collection>>(`/${type}?${params({ lifecycle: 'trashed', limit: 20, offset })}`), api = useApi(), refresh = useRefresh()
  async function restore(item: Card | Collection) { try { await api(`/${type}/${item.id}/lifecycle`, 'POST', { expected_revision: item.revision, action: 'restore' }); await refresh() } catch (e) { setMessage((e as Error).message) } }
  return <><PageHeading title="回收站" description="恢复后，卡片的连接、合集归属和学习历史仍然保留。"><Link to="/settings">返回设置</Link></PageHeading><div className="panel single-form"><div className="segmented"><button className={type === 'cards' ? 'selected' : ''} onClick={() => { setType('cards'); setOffset(0) }}>卡片</button><button className={type === 'collections' ? 'selected' : ''} onClick={() => { setType('collections'); setOffset(0) }}>合集</button></div><p role="status">{message}</p><QueryState query={query}>{query.data?.items.map(c => <div className="directory-row" key={c.id}><div><b>{c.title}</b></div><button onClick={() => void restore(c)}>恢复</button></div>)}{!query.data?.total && <p className="state">回收站是空的。</p>}</QueryState><div className="pager"><button disabled={!offset} onClick={() => setOffset(offset - 20)}>上一页</button><button disabled={offset + 20 >= (query.data?.total || 0)} onClick={() => setOffset(offset + 20)}>下一页</button></div></div></>
}
function TaxonomySettings() {
  const [type, setType] = useState('topics'), [message, setMessage] = useState(''), api = useApi(), refresh = useRefresh(), query = useData<{ items: Label[] }>(`/${type}`)
  async function edit(label: Label, remove = false) { const name = remove ? null : window.prompt('新名称', label.name); if (!remove && !name) return; try { await api(`/${type}/${label.id}`, remove ? 'DELETE' : 'PATCH', remove ? undefined : { name }); await refresh() } catch (e) { setMessage((e as Error).message) } }
  return <section className="panel single-form"><h2>分类与标签管理</h2><div className="segmented"><button onClick={() => setType('topics')} className={type === 'topics' ? 'selected' : ''}>分类 / 主题</button><button onClick={() => setType('tags')} className={type === 'tags' ? 'selected' : ''}>标签</button></div><p role="status">{message}</p><QueryState query={query}>{query.data?.items.map(t => <div className="directory-row" key={t.id}><div>{t.name} <small>{t.kind === 'knowledge' ? '知识分类' : t.kind === 'opinion' ? '观点主题' : ''}</small></div><button onClick={() => void edit(t)}>重命名</button><button onClick={() => void edit(t, true)}>删除</button></div>)}</QueryState></section>
}
