import { Link, useSearchParams } from 'react-router-dom'
import { useData, params, showDate, type Card, type Page, type Label } from '../../lib/workspace'
import { Icon, PageHeading, Pager, QueryState, Tags } from '../../components/Common'
import { CardDetail } from '../cards/Detail'

export default function Opinions() {
  const [search, setSearch] = useSearchParams(), topic = search.get('topic') || '', q = search.get('q') || '', selected = search.get('card')
  const topics = useData<{ items: Label[] }>('/topics?kind=opinion')
  const cards = useData<Page<Card>>(`/cards?${params({ kind: 'opinion', topic_id: topic, q, processing_state: search.get('state'), sort: search.get('sort') || 'updated_desc', limit: 12, offset: Number(search.get('offset') || 0) })}`)
  const total = useData<{ opinions: number; inbox: number }>('/cards/summary')
  function update(key: string, value: string) { const next = new URLSearchParams(search); if (value) next.set(key, value); else next.delete(key); if (key !== 'offset' && key !== 'card') next.delete('offset'); setSearch(next) }
  return <><PageHeading title="观点" description="一个想法，一张卡片。让独立的思考彼此连接。"><Link className="button primary" to="/new?kind=opinion">＋ 写下观点</Link></PageHeading><div className={`workspace-layout opinion-layout ${selected ? 'has-selection' : ''}`}><aside className="sidebar"><p className="eyebrow">我的卡片盒</p><button className={!topic && !search.get('state') ? 'active' : ''} onClick={() => setSearch({})}><Icon name="card"/>全部观点<span>{total.data?.opinions ?? '—'}</span></button><button className={search.get('state') === 'inbox' ? 'active' : ''} onClick={() => update('state', search.get('state') ? '' : 'inbox')}><Icon name="clock"/>待整理</button><div className="sidebar-divider"/><p className="eyebrow">主题</p><QueryState query={topics}>{topics.data?.items.map(t => <button className={topic === t.id ? 'active' : ''} key={t.id} onClick={() => update('topic', t.id)}><span className="category-dot"/>{t.name}<span>{t.card_count}</span></button>)}</QueryState><Link className="sidebar-add" to="/new?kind=opinion">＋ 新建原子观点</Link><div className="sidebar-note"><Icon name="link"/><h3>思考，在连接中生长。</h3><p>把想法写成自己的语言，并为它找到下一个连接。</p></div></aside>
    <section className="opinion-list"><div className="toolbar"><div className="search-box"><Icon name="search"/><input aria-label="搜索观点" value={q} onChange={e => update('q', e.target.value)} placeholder="搜索观点、关键词…"/></div><select aria-label="观点排序" value={search.get('sort') || 'updated_desc'} onChange={e => update('sort', e.target.value)}><option value="updated_desc">最近更新</option><option value="connections_desc">连接最多</option><option value="created_desc">最近创建</option></select></div><div className="section-title"><h2>{topic ? topics.data?.items.find(t => t.id === topic)?.name : '全部观点'} <small>{cards.data?.total ?? 0} 张卡片</small></h2></div><QueryState query={cards} empty={cards.data?.total === 0}><div className="opinion-cards">{cards.data?.items.map(c => <button className={`opinion-card ${selected === c.id ? 'selected' : ''}`} key={c.id} onClick={() => update('card', c.id)}><div className="card-meta"><span>{c.topics[0]?.name || '未分类'}</span><small>{c.processing_state === 'inbox' ? '待整理' : '已整理'}</small></div><h3>{c.title}</h3><p className="excerpt">{c.excerpt}</p><Tags items={c.tags}/><div className="opinion-footer"><span><Icon name="link"/>{(c.link_count || 0) + (c.backlink_count || 0)} 个连接</span><time>{showDate(c.updated_at)}</time></div></button>)}</div>{cards.data && <Pager {...cards.data} onChange={n => update('offset', String(n))}/>}</QueryState></section>
    <aside className="opinion-detail">{selected ? <><button className="mobile-back" onClick={() => update('card', '')}>← 返回观点列表</button><CardDetail key={selected} id={selected} compact/></> : <div className="state"><Icon name="link"/><h3>打开一张观点卡片</h3><p>阅读正文，看看它连接了哪些知识与思考。</p></div>}</aside></div></>
}
